server:
  port: 5051
spring:
  datasource:
    initialization-mode: always
    password: 123_Stella
    platform: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
logging:
  level:
    com:
      xantrix:
        webapp:
          controller:
            PriceClient: DEBUG
gestuser :
    srvUrl : http://localhost:8019/api/utenti/cerca/userId/
    userId : Admin
    password : MagicaBula_2018

sicurezza:
  uri: /auth
  refresh: /refresh
  header: Authorization
  prefix: Bearer
  expiration: 86400
  secret: 123_Stella

